#!/bin/bash

robot --catalog catalog-v001.xml convert -I https://storage.googleapis.com/public-download-files/hgnc/owl/owl/hgnc.owl -o tmp/mirror-hgnc.owl
mkdir -p mirror
if [ -f tmp/mirror-hgnc.owl ]; then if cmp -s tmp/mirror-hgnc.owl mirror/hgnc.owl ; then echo "Mirror identical, ignoring."; else echo "Mirrors different, updating." &&\
        cp tmp/mirror-hgnc.owl mirror/hgnc.owl; fi; fi
# Mirrors different, updating.

# Extract terms from the source OBO file, and merge with the terms from the mirror. 
# This is needed to ensure that we have all the terms that are in the source OBO file, even if they are not in the mirror.
robot --catalog catalog-v001.xml \
        convert --input immunotest-edit.obo --format ofn --output tmp/immunotest-preprocess.owl
robot --catalog catalog-v001.xml \
        remove --input tmp/immunotest-preprocess.owl --select imports --trim false \
        merge --output tmp/merged-immunotest-edit.ofn
robot --catalog catalog-v001.xml \
        query --input tmp/merged-immunotest-edit.ofn --format --csv \
               --query ../sparql/terms.sparql tmp/pre_seed.txt
cat tmp/pre_seed.txt | sort | uniq > tmp/seed.txt

robot --catalog catalog-v001.xml \
        annotate --input mirror/hgnc.owl --remove-annotations \
        odk:normalize --add-source true \
        extract --term-file imports/hgnc_terms.txt --term-file tmp/seed.txt \
                --force true --copy-ontology-annotations true --individuals include --method BOT \
        remove  --term rdfs:label  --term IAO:0000115  --term OMO:0002000 \
                --term-file imports/hgnc_terms.txt --term-file tmp/seed.txt \
                --select complement --select annotation-properties \
        odk:normalize --base-iri http://purl.obolibrary.org/obo \
                --subset-decls true --synonym-decls true \
        repair --merge-axiom-annotations true \
        annotate --ontology-iri http://purl.obolibrary.org/obo/immunotest/imports/hgnc_import.owl \
        annotate -V http://purl.obolibrary.org/obo/immunotest/releases/2026-03-16/imports/hgnc_import.owl \
                --annotation owl:versionInfo 2026-03-16 \
        convert -f ofn --output imports/hgnc_import.owl.tmp.owl \
        && mv imports/hgnc_import.owl.tmp.owl imports/hgnc_import.owl
robot --catalog catalog-v001.xml \
        merge --input tmp/immunotest-preprocess.owl  \
        reason --reasoner ELK --equivalent-classes-allowed asserted-only --exclude-tautologies structural \
        relax --include-subclass-of true \
        reduce -r ELK --include-subproperties true \
        annotate --ontology-iri http://purl.obolibrary.org/obo/immunotest/immunotest-full.owl \
        annotate -V http://purl.obolibrary.org/obo/immunotest/releases/2026-03-16/immunotest-full.owl \
                --annotation owl:versionInfo 2026-03-16 --output immunotest-full.owl.tmp.owl \
        && mv immunotest-full.owl.tmp.owl immunotest-full.owl
robot --catalog catalog-v001.xml \
        annotate --input immunotest-full.owl --ontology-iri http://purl.obolibrary.org/obo/immunotest.owl \
        annotate -V http://purl.obolibrary.org/obo/immunotest/releases/2026-03-16/immunotest.owl \
                --annotation owl:versionInfo 2026-03-16 \
        convert -o immunotest.owl.tmp.owl && mv immunotest.owl.tmp.owl immunotest.owl
robot --catalog catalog-v001.xml \
        convert --input immunotest.owl --check false -f obo --clean-obo "strict drop-untranslatable-axioms" -o immunotest.obo
robot --catalog catalog-v001.xml \
        merge --input tmp/immunotest-preprocess.owl  \
        reason --reasoner ELK --equivalent-classes-allowed asserted-only --exclude-tautologies structural --annotate-inferred-axioms false \
        relax --include-subclass-of true \
        reduce -r ELK --include-subproperties true \
        remove --base-iri http://purl.obolibrary.org/obo/IMMUNOTEST --axioms external --preserve-structure false --trim false \
        annotate --link-annotation http://purl.org/dc/elements/1.1/type http://purl.obolibrary.org/obo/IAO_8000001 \
                --ontology-iri http://purl.obolibrary.org/obo/immunotest/immunotest-base.owl \
        annotate -V http://purl.obolibrary.org/obo/immunotest/releases/2026-03-16/immunotest-base.owl \
                --annotation owl:versionInfo 2026-03-16 --output immunotest-base.owl.tmp.owl \
        && mv immunotest-base.owl.tmp.owl immunotest-base.owl
robot --catalog catalog-v001.xml \
        convert --input immunotest-base.owl --check false -f obo --clean-obo "strict drop-untranslatable-axioms" -o immunotest-base.obo
robot --catalog catalog-v001.xml \
        convert --input immunotest-full.owl --check false -f obo --clean-obo "strict drop-untranslatable-axioms" -o immunotest-full.obo
mkdir -p reports
robot --catalog catalog-v001.xml \
        report -i tmp/merged-immunotest-edit.ofn -l true  --fail-on None \
                --base-iri http://purl.obolibrary.org/obo/IMMUNOTEST_ \
                --base-iri http://purl.obolibrary.org/obo/immunotest \
                --print 5 -o reports/immunotest-edit.obo-obo-report.tsv
